sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-086
env:
  global:
    -
      # LTD_AWS_ID
      secure: iV1z84pNv041ctDHiPRmKWVASXsKGNTk0oyXITIrS5vfdB9hkHzFU39w1lsNUte3Z+bpgiYwNwWj2JcgnOaXPmZKIRw8x/s2V3wWG5dSUPt/H1W/DX6UiaEkWMWyl8OM030BDgwE4wzJMfbYm7h4lFu72eheXVXF4V7PXbK/efIIx2IqkjJeVkMop1e7csPHSzGesAOKkGGmpIj5OZmfuXPSAPKB9CL0SYoO/oBO4qw4h6kQwZMMZ0VG3LGr39gkUfWlkGQ2ZX3c5CiArmAE2HLUqcgVVM0uYOoAirSBUckGc50wtqAb4xkZfom69ZLSytuweTGLTHM6KvwZEc2dizua57F9mw0DNTNLK47fkCxX386xejv5SFaJlHIPmeS8X99YtS0LWxTc+j+F7zFwuCzhHdI2NLp0rTQkn1wA+7rLqfUsCaf1l/zjm3djV24NWevkxH3+cRRnXlzOQ1q3+jGFvRogYG3HEtN5LtTvqYRsxyiowmbiYxiTJnH0hpteQtpJGBzy1Jg9txgwGBpV1DTho8bUdL45iq/AaJSmsqIkOaejK5yCCIuoNezIEOPgjkTfmIf8jyt2dRPxuDpntc1CfJZHK/RvTOQ3JabicoA2Q13HXkGz+GXxDPVcmEITDEdOZNJ6qkVeF8iIRz6UXmc4P/fO1uRfXWnyTD3cf2Y=
    -
      # LTD_AWS_SECRET
      secure: YCe5N3YC2o5EYHgkIJTLJOfLa5FFaH+sIdN8BEimIvlK3eCNiSPI+a/p4PsE6QafYBQ1BoRrJ0nrpnKxTfXONXtH90B+i0XVCEPdfA/H91usJjLa8F7FhihAFcL3WUKBSzZrSKjaFQFlDFCqUEiqTeX46bIBEarh7wgC0zJpMxU5sf99iZ60ciH6KfLfCygiC5JwfjH/ypeksIvu+6/I46O1xjvL0tp7oYZbaSti5GCkPFRj6Vw6wiizdT6JjZ9/XqTYTQVKyvhwaPitvjiYw9dQYujOiFsNQdWusshMnvlblUkV58IP5TJEukgeY32HQ/09tHcOshke+R46rweDNKaGigaFWGQ2nPj9Vvx77LfveH+TBZPEfpRfpvOlJmWn2UdrpJTzQCdeqg9kpXHNCaQSzOrXpxDUpfZf66VGXovt18bipGNTK3mujwIXeDEXhbbVkQZzlbBDHkXoodWjHTS2FE933BPhtDn0msKTfZ0UFoTRWSzoO9+EOPrPOTVgaU4uYpdOnwW5H7P9kr85E12YyVQG2og0z2ZhuqNlMoZu5NSh4EoW3vZe4ZsCDwL8cjRUQt9Hw8zyqm78/z51Ggnn5mPfQR5zGKWbjhfIgbHsIoT+ZDXqFrblK3CBDg2WjdMxjHFyllnHTskv0RdthRu3CrahlfHIq0cJQ9nnX9E=
    -
      # LTD_USERNAME
      secure: tDgF2ItppaXm7QgQMsWPgPVYN2PlRUvb9V9Z/KWEZwOxQNHvIDxZYjXP6wz2Vn7hyLK/i9iCYzzn8fi9V+TSEzhA9nlC/LWoLjlurKO+m1lUoXTsTNK90pjJ2gp26HKC9mNFbfjhJyaByV82JVT4k9KF9j0gUwGJys61+ycTHbhAB3NOZsFMF3l5PJQF44YCeP3yAwJ6rNz2/WBQKy5+l6obfQrCN4gfxWNJzwAC9kZGz8uMMHHFu3wspUT3o9IL91n0cxPrrs94OimyqRFcPJyCfv/K8/11vAoFHhVvPQzK2fwm87DePOqFzsKNrzaaZVMc1Gv5wQJ6SjZGqc1szqRcbZQgOT6gOWbEVOv2u5/fcTsswEjv/pgpaJ5b6bAukpYBFJfaiya+1JYXAkkz2zvVkPBmKoVm0U2vOfpoXPPHqOfpEWhw05kmnbg5icg+hTHZ3+t6L7miQomxyEmoGLrH6w0+sj38pX81jzP5tIZTp2GIS32kU6OUPvmv+oqZ3qB/9Qxo9HbN5YOC6RJWE6KzR1AcAR+7sgVBcfqhHdRu4ddQZyrZuOUyy5oraKzkcb7A1n/nWTdewHWq6UNe8cRIB9BQyaO9QGNC9/YIRJt7gD25WgCI8kFmDp/EgBEmbTZZ7+tNjYCJpu2ZU3zWK/XKQl/msmy8i+44ZPbQp/Q=
    -
      # LTD_PASSWORD
      secure: WMdWbaEI4OZxo9v2CnNnKt1uGSQVSwFnZMZSSbQcRx9Z1qiXB+V3X7kh3tpdiH7e/3uxCAhhBY5uRMIPpIFeTj7H/XhEMN503G7e4F9ObOg2Yo45+ZvREfzEUkBE0zQmO8g5JP0q9fx0mzWCn2CJc/C66PNDP/3j6OJm+os4d5L1iQcQD70YGxFmkzeI329tUJ6OeI1f7sV+uV7f6Obmu9ldX+nOlCAW1yaLl8krXXdyYRhtkdOT/4SNv1WrC09RDE9NjQPvccRbMyEgbYUsIo0xs3m8rRX1p1ORIJMOACzYDB/I1djedguKNgRsVZa9w+5vP4s5dm6jio3qu7OcYZQxYoFJooK1tsPtjK685ityMRSyWY8QPHyKM+5fOzKFUgN1HH9QS4oHSoOja4OX4Iv+w/qhEwtnPKAhIX0JEFPD7+A/kcLdwqrK4jb3ZECH2JN9SGTJGw31FE63ZVDt+y0qNnh95N7V92IrxJJptNsFfXySJM0RMmhyghjrZR9z1DxREe6BOmDn1AR04PiiGFCTeBDwi9pNXyTXn3GD+M/GwTh7tMsOch+MIZpMNz5KjtgZij0jC1hFV+J49A6Cq0cDlwH3Uiz0wiAqXTAhThg+b6nbffObtd6uxpxrUVDRTEp7tOGCB2lfAieUkMdFHlwV+djcD9xcpG1aVSNSZZI=
